[package]
name = "d3bug-2"
version = "0.1.0"
edition = "2021"

[dependencies]
elf = "0.7.4"
gimli = "0.31.1"
memmap2 = "0.9.5"
nix = { version = "0.29.0", features = ["ptrace", "process"] }
object = "0.36.5"
